swagger: "2.0"
info:
  description: '<font size="2" color="red">MIT Licença</font>'
  version: "1.0.3"
  title: "Tracking Api"
  license:
    name: "REST TO SOAP"
    url: "https://github.com/lucioerlan"
host: "localhost:5000"
basePath: "/api"
schemes:
  - "http"
paths:
  /tracking/:
    get:
      tags:
        - "ROUTES"
      summary: "Response to the request on mongoDB"
      description: "Get all tracking"
      operationId: "get-tracking"
      produces:
        - "application/xml"
        - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"

    post:
      tags:
        - "ROUTES"
      summary: "Post tracking."
      description: "Insert a tracking"
      operationId: "post-tracking"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "List of tracking"
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/tracking"
      responses:
        default:
          description: "successful operation"

definitions:
  tracking:
    type: "object"
    required:
      - "id"
      - "tracking"
      - "lat"
      - "lon"
    properties:
      id:
        type: "string"
      tracking:
        type: "string"
      lat:
        type: "number"
        multipleOf: 2.5
      lon:
        type: "number"
        multipleOf: 2.5
      plate:
        type: "string"
